
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Asus
 */
public class teacher_home extends javax.swing.JFrame {

    /**
     * Creates new form teacher_home
     */
    public teacher_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        home = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        grade = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        course = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        attendence = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        class_sc = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        grade_s = new javax.swing.JPanel();
        grade_sheet = new javax.swing.JLabel();
        course_reg = new javax.swing.JPanel();
        course_r = new javax.swing.JLabel();
        attendence_s = new javax.swing.JPanel();
        student_a = new javax.swing.JLabel();
        class_scd = new javax.swing.JPanel();
        class_s = new javax.swing.JLabel();
        profile_teacher = new javax.swing.JPanel();
        profile_p = new javax.swing.JLabel();
        pass_label = new javax.swing.JPanel();
        change = new javax.swing.JLabel();
        home_logout = new javax.swing.JPanel();
        logout = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Teacher Portal Home");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(245, 249, 221));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(32767, 32767));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled2.png"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Untitled4.png"))); // NOI18N

        home.setBackground(new java.awt.Color(102, 153, 255));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("       Home");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        grade.setBackground(new java.awt.Color(245, 249, 221));
        grade.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                gradeMouseDragged(evt);
            }
        });
        grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                gradeMouseEntered(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel6.setText("Grade Sheet Entry");

        javax.swing.GroupLayout gradeLayout = new javax.swing.GroupLayout(grade);
        grade.setLayout(gradeLayout);
        gradeLayout.setHorizontalGroup(
            gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        gradeLayout.setVerticalGroup(
            gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradeLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        course.setBackground(new java.awt.Color(245, 249, 221));
        course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                courseMouseClicked(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(245, 249, 221));
        jLabel7.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel7.setText("Course Registration");

        javax.swing.GroupLayout courseLayout = new javax.swing.GroupLayout(course);
        course.setLayout(courseLayout);
        courseLayout.setHorizontalGroup(
            courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        courseLayout.setVerticalGroup(
            courseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, courseLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        attendence.setBackground(new java.awt.Color(245, 249, 221));
        attendence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendenceMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel8.setText("Students Attendence");

        javax.swing.GroupLayout attendenceLayout = new javax.swing.GroupLayout(attendence);
        attendence.setLayout(attendenceLayout);
        attendenceLayout.setHorizontalGroup(
            attendenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        attendenceLayout.setVerticalGroup(
            attendenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, attendenceLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        class_sc.setBackground(new java.awt.Color(245, 249, 221));
        class_sc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                class_scMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel9.setText("Class Schedule");

        javax.swing.GroupLayout class_scLayout = new javax.swing.GroupLayout(class_sc);
        class_sc.setLayout(class_scLayout);
        class_scLayout.setHorizontalGroup(
            class_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        class_scLayout.setVerticalGroup(
            class_scLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, class_scLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        profile.setBackground(new java.awt.Color(245, 249, 221));
        profile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileMouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel10.setText("Profile");

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        jLabel12.setText("You are logged in as:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Md.Ansarul Islam");

        jLabel16.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel16.setText("TeacherID:");

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel17.setText("01303354189");

        jLabel18.setFont(new java.awt.Font("Calibri", 1, 17)); // NOI18N
        jLabel18.setText("Teacher Name:");

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 17)); // NOI18N
        jLabel19.setText("Md.Ansalul Islam");

        grade_s.setBackground(new java.awt.Color(245, 249, 221));
        grade_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grade_sMouseClicked(evt);
            }
        });

        grade_sheet.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        grade_sheet.setForeground(new java.awt.Color(51, 153, 0));
        grade_sheet.setText("Grade Sheet Entry");
        grade_sheet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grade_sheetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout grade_sLayout = new javax.swing.GroupLayout(grade_s);
        grade_s.setLayout(grade_sLayout);
        grade_sLayout.setHorizontalGroup(
            grade_sLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grade_sLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(grade_sheet)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        grade_sLayout.setVerticalGroup(
            grade_sLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(grade_sLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(grade_sheet)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        course_reg.setBackground(new java.awt.Color(245, 249, 221));
        course_reg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                course_regMouseClicked(evt);
            }
        });

        course_r.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        course_r.setForeground(new java.awt.Color(51, 153, 0));
        course_r.setText("Course Registration");

        javax.swing.GroupLayout course_regLayout = new javax.swing.GroupLayout(course_reg);
        course_reg.setLayout(course_regLayout);
        course_regLayout.setHorizontalGroup(
            course_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(course_regLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(course_r)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        course_regLayout.setVerticalGroup(
            course_regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(course_regLayout.createSequentialGroup()
                .addComponent(course_r)
                .addGap(0, 5, Short.MAX_VALUE))
        );

        attendence_s.setBackground(new java.awt.Color(245, 249, 221));
        attendence_s.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendence_sMouseClicked(evt);
            }
        });

        student_a.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        student_a.setForeground(new java.awt.Color(51, 153, 0));
        student_a.setText("Student Attendence");

        javax.swing.GroupLayout attendence_sLayout = new javax.swing.GroupLayout(attendence_s);
        attendence_s.setLayout(attendence_sLayout);
        attendence_sLayout.setHorizontalGroup(
            attendence_sLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendence_sLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(student_a)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        attendence_sLayout.setVerticalGroup(
            attendence_sLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendence_sLayout.createSequentialGroup()
                .addComponent(student_a)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        class_scd.setBackground(new java.awt.Color(245, 249, 221));
        class_scd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                class_scdMouseClicked(evt);
            }
        });

        class_s.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        class_s.setForeground(new java.awt.Color(51, 153, 0));
        class_s.setText("Class Schedule");

        javax.swing.GroupLayout class_scdLayout = new javax.swing.GroupLayout(class_scd);
        class_scd.setLayout(class_scdLayout);
        class_scdLayout.setHorizontalGroup(
            class_scdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(class_scdLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(class_s)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        class_scdLayout.setVerticalGroup(
            class_scdLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(class_scdLayout.createSequentialGroup()
                .addComponent(class_s)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        profile_teacher.setBackground(new java.awt.Color(245, 249, 221));
        profile_teacher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profile_teacherMouseClicked(evt);
            }
        });

        profile_p.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        profile_p.setForeground(new java.awt.Color(51, 153, 0));
        profile_p.setText("My Profile ");

        javax.swing.GroupLayout profile_teacherLayout = new javax.swing.GroupLayout(profile_teacher);
        profile_teacher.setLayout(profile_teacherLayout);
        profile_teacherLayout.setHorizontalGroup(
            profile_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_teacherLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(profile_p)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        profile_teacherLayout.setVerticalGroup(
            profile_teacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profile_teacherLayout.createSequentialGroup()
                .addComponent(profile_p)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pass_label.setBackground(new java.awt.Color(245, 249, 221));

        change.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        change.setForeground(new java.awt.Color(51, 153, 0));
        change.setText("Change Password");
        change.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                changeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pass_labelLayout = new javax.swing.GroupLayout(pass_label);
        pass_label.setLayout(pass_labelLayout);
        pass_labelLayout.setHorizontalGroup(
            pass_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pass_labelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(change)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pass_labelLayout.setVerticalGroup(
            pass_labelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pass_labelLayout.createSequentialGroup()
                .addComponent(change)
                .addGap(0, 84, Short.MAX_VALUE))
        );

        home_logout.setBackground(new java.awt.Color(245, 249, 221));
        home_logout.setPreferredSize(new java.awt.Dimension(100, 11));
        home_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                home_logoutMouseClicked(evt);
            }
        });

        logout.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        logout.setForeground(new java.awt.Color(153, 51, 255));
        logout.setText("(Log out)");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout home_logoutLayout = new javax.swing.GroupLayout(home_logout);
        home_logout.setLayout(home_logoutLayout);
        home_logoutLayout.setHorizontalGroup(
            home_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_logoutLayout.createSequentialGroup()
                .addComponent(logout)
                .addGap(0, 56, Short.MAX_VALUE))
        );
        home_logoutLayout.setVerticalGroup(
            home_logoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_logoutLayout.createSequentialGroup()
                .addComponent(logout, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jLabel29.setFont(new java.awt.Font("Arial Black", 2, 10)); // NOI18N
        jLabel29.setText("UI Designed by: Kaiyum & Hasib");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 51, 255));
        jLabel11.setText("Home");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(grade_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel13)
                        .addGap(5, 5, 5)
                        .addComponent(home_logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(264, 264, 264)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(514, 514, 514)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel17))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 1198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(997, 997, 997)
                        .addComponent(jLabel29))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(491, 491, 491)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(473, 473, 473)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(course_reg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(attendence_s, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(class_scd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(profile_teacher, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(class_sc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(attendence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(class_sc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(profile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(7, 7, 7)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(home_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(grade_s, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(course_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(attendence_s, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(class_scd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(profile_teacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(pass_label, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141)
                .addComponent(jLabel29)
                .addGap(7, 7, 7)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked

        // TODO add your handling code here:
        close();
    teacher_home hom = new teacher_home();
    hom.setVisible(true);
    }//GEN-LAST:event_homeMouseClicked

    private void gradeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeMouseDragged

    private void gradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeMouseClicked

     close();
    grade gr = new grade();
    gr.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeMouseClicked

    private void gradeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeMouseEntered

    private void courseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseMouseClicked
    close();
    course cou = new course();
    cou.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_courseMouseClicked

    private void attendenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceMouseClicked

        // TODO add your handling code here:
        close();
    attendance att = new attendance();
    att.setVisible(true);
    }//GEN-LAST:event_attendenceMouseClicked

    private void class_scMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_scMouseClicked

        // TODO add your handling code here:
    close();
    class_scdule cls = new class_scdule();
    cls.setVisible(true);
    }//GEN-LAST:event_class_scMouseClicked

    private void profileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileMouseClicked

  // TODO add your handling code here:
      close();
    profile_teacher pr = new profile_teacher();
    pr.setVisible(true);
    }//GEN-LAST:event_profileMouseClicked

    private void grade_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grade_sMouseClicked
    
        // TODO add your handling code here:
        close();
    grade gr = new grade();
    gr.setVisible(true);
    }//GEN-LAST:event_grade_sMouseClicked

    private void course_regMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_course_regMouseClicked
     
        // TODO add your handling code here:
        close();
    course cou = new course();
    cou.setVisible(true);
    }//GEN-LAST:event_course_regMouseClicked

    private void attendence_sMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendence_sMouseClicked
       
        // TODO add your handling code here:
        close();
    attendance att = new attendance();
    att.setVisible(true);
    }//GEN-LAST:event_attendence_sMouseClicked

    private void class_scdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_class_scdMouseClicked
    
        // TODO add your handling code here:
         close();
    class_scdule cls = new class_scdule();
    cls.setVisible(true);
    }//GEN-LAST:event_class_scdMouseClicked

    private void profile_teacherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profile_teacherMouseClicked
       // TODO add your handling code here:
        close();
    profile_teacher pr = new profile_teacher();
    pr.setVisible(true);
    }//GEN-LAST:event_profile_teacherMouseClicked

    private void changeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_changeMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You can't change your Password because there is no database connection...!");
    }//GEN-LAST:event_changeMouseClicked

    private void home_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_logoutMouseClicked

    }//GEN-LAST:event_home_logoutMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        // TODO add your handling code here:
        close();
        teacher_login sp= new teacher_login();
        sp.setVisible(true);
    }//GEN-LAST:event_logoutMouseClicked

    private void grade_sheetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grade_sheetMouseClicked
        // TODO add your handling code here:
        close();
        grade gr=new grade();
        gr.setVisible(true);
        
    }//GEN-LAST:event_grade_sheetMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacher_home().setVisible(true);
            }
        });
    }
    
    public void close()
    {
        
        WindowEvent closeWindow= new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel attendence;
    private javax.swing.JPanel attendence_s;
    private javax.swing.JLabel change;
    private javax.swing.JLabel class_s;
    private javax.swing.JPanel class_sc;
    private javax.swing.JPanel class_scd;
    private javax.swing.JPanel course;
    private javax.swing.JLabel course_r;
    private javax.swing.JPanel course_reg;
    private javax.swing.JPanel grade;
    private javax.swing.JPanel grade_s;
    private javax.swing.JLabel grade_sheet;
    private javax.swing.JPanel home;
    private javax.swing.JPanel home_logout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel pass_label;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel profile_p;
    private javax.swing.JPanel profile_teacher;
    private javax.swing.JLabel student_a;
    // End of variables declaration//GEN-END:variables
}
